### ISSUE TITLE
entimport: schema import failed - mysql: parse precision "unsigned"

### ISSUE THREAD

**Issue by taofei-pro** [ariga/entimport#10]

**Comment by zeevmoney** [comment]
Hi @taofei-pro,

It's most likely solved in a new version of Atlas, I'll try to update the Atlas dep to `@master` and release it this/next week.
You are welcome to do a PR if you want.

**Comment by taofei-pro** [comment]
@zeevmoney 

I found that the -tables parameters do not take effect, and multiple tables are still generated

**Comment by taofei-pro** [comment]
https://github.com/ariga/atlas

Is it the problem with this repository?

**Comment by zeevmoney** [comment]
@taofei-pro, can you please show the full command that you've executed (without private info) and an example of your schema (the field names don't matter, just the types)?

> https://github.com/ariga/atlas
> 
> Is it the problem with this repository?

I was referring to this repository, yes.

**Comment by taofei-pro** [comment]
@zeevmoney 

entimport -dialect mysql -dsn "root:pass@tcp(localhost:3306)/test" -schema-path ./ent/schema -tables "users"

After I interrupted, I found that there was still a problem with this repository.

https://github.com/ariga/atlas/issues/347

**Comment by zeevmoney** [comment]
> @zeevmoney
> 
> entimport -dialect mysql -dsn "root:pass@tcp(localhost:3306)/test" -schema-path ./ent/schema -tables "users"
> 
> After I interrupted, I found that there was still a problem with this repository.
> 
> [ariga/atlas#347](https://github.com/ariga/atlas/issues/347)

@taofei-pro I've upgraded the Atlas dep to the newest version. Can you please check if the issue still exist?

**Comment by taofei-pro** [comment]
@zeevmoney
Solved, great, thank you
